name: Build and Push Docker Image

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'CLAUDE.md'
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  GITEA_REGISTRY: git.home.mikelamoureux.net
  IMAGE_NAME: unraid-mcp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ secrets.WORKFLOW_BOT_USERNAME }}
          password: ${{ secrets.WORKFLOW_BOT_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.GITEA_REGISTRY }}/mike/${{ env.IMAGE_NAME }}:latest
            ${{ env.GITEA_REGISTRY }}/mike/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.GITEA_REGISTRY }}/mike/${{ env.IMAGE_NAME }}-cache:latest
          cache-to: type=registry,ref=${{ env.GITEA_REGISTRY }}/mike/${{ env.IMAGE_NAME }}-cache:latest,mode=max
          platforms: linux/amd64

      - name: Trigger stack redeployment via Semaphore
        run: |
          # Trigger restart_stack.yml template (ID: 17) on Semaphore
          response=$(curl -s -w "\n%{http_code}" -X POST "${{ secrets.SEMAPHORE_API_URL }}/api/project/2/tasks" \
            -H "Authorization: Bearer ${{ secrets.SEMAPHORE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "template_id": 17,
              "environment": "{\"docker_host\": \"common-services.home.mikelamoureux.net\", \"restart_stack\": \"mcp-gateway\"}"
            }')
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          echo "Response: $body"
          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "Successfully triggered redeployment of mcp-gateway stack on common-services"
          else
            echo "Failed to trigger redeployment (HTTP $http_code)"
            exit 1
          fi
