name: Build and Push Docker Image

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'CLAUDE.md'
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  GITEA_REGISTRY: git.home.mikelamoureux.net
  IMAGE_NAME: unraid-mcp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ secrets.WORKFLOW_BOT_USERNAME }}
          password: ${{ secrets.WORKFLOW_BOT_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.GITEA_REGISTRY }}/mike/${{ env.IMAGE_NAME }}:latest
            ${{ env.GITEA_REGISTRY }}/mike/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.GITEA_REGISTRY }}/mike/${{ env.IMAGE_NAME }}-cache:latest
          cache-to: type=registry,ref=${{ env.GITEA_REGISTRY }}/mike/${{ env.IMAGE_NAME }}-cache:latest,mode=max
          platforms: linux/amd64
