name: Build and Deploy to Gitea Registry

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'CLAUDE.md'
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  GITEA_REGISTRY: git.home.mikelamoureux.net
  PROJECT_NAME: unraid-mcp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ secrets.WORKFLOW_BOT_USERNAME }}
          password: ${{ secrets.WORKFLOW_BOT_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.GITEA_REGISTRY }}/mike/${{ env.PROJECT_NAME }}:latest
            ${{ env.GITEA_REGISTRY }}/mike/${{ env.PROJECT_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.GITEA_REGISTRY }}/mike/${{ env.PROJECT_NAME }}-cache:latest
          cache-to: type=registry,ref=${{ env.GITEA_REGISTRY }}/mike/${{ env.PROJECT_NAME }}-cache:latest,mode=max
          platforms: linux/amd64

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Authenticate to Vault and retrieve Semaphore token
        id: vault
        run: |
          VAULT_TOKEN=$(curl -s -X POST ${{ secrets.VAULT_ADDR }}/v1/auth/approle/login -d "{\"role_id\":\"${{ secrets.VAULT_ROLE_ID }}\",\"secret_id\":\"${{ secrets.VAULT_SECRET_ID }}\"}" | jq -r '.auth.client_token')
          SEMAPHORE_TOKEN=$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" ${{ secrets.VAULT_ADDR }}/v1/homelab/data/gitea-actions/semaphore-api-key | jq -r '.data.data.token')
          echo "SEMAPHORE_TOKEN=$SEMAPHORE_TOKEN" >> $GITHUB_ENV

      - name: Trigger Ansible Semaphore Stack Restart
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://semaphore.ansible.home.mikelamoureux.net/api/project/2/tasks'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ env.SEMAPHORE_TOKEN }}"}'
          data: '{"template_id": 17, "environment": "{\"docker_host\": \"common-services.home.mikelamoureux.net\", \"restart_stack\": \"mcp-gateway\"}"}'
